### ISSUE TITLE
PC 및 IE 관련 대응 문의

### ISSUE THREAD

**Issue by trustyoo86** [kooljay82/ugly-calendar#5]
### 이슈내용
PC 대응 관련 문의 및 건의

### 상세
모듈 확인 중에 관련되어 PC 및 IE 대응이 추후에 가능할지 문의드립니다. 
일부 함수 및 기능의 경우 polyfill 적용 하더라도 반영이 안되는(Object.propertyIsEnumerble과 같은) 이슈들이 있었어서, 현재 모바일 이후에 작업되는 부분에 대한 영역을 저희쪽에서도 같이 확인 해 봐야 할것 같아서, 관련 부분 미리 공유합니다 :)

**Comment by kooljay82** [comment]
말씀해주신대로 해당 프로젝트는 아직은 PC 및 IE 대응이 아직 안된상태입니다. 아울러 말씀해주신 부분의 구현부는 polyfill이 완벽하게 이뤄지지 않을 부분으로 계획했던 주요 기능들을 완료한 후 PC UI 기본작업과 IE 대응 방안을 마련할 예정입니다. 

감사합니다.
